import { useRouter } from 'next/router'
import Head from 'next/head'
import { ParsedUrlQuery } from 'querystring'
import { GetStaticProps, GetStaticPaths } from 'next'
import styles from '../../styles/AboutMe.module.css'

interface IPropsAboutMeDetail {
    aboutMeDetail?: { message?: string; title?: string, id?: string }
}

interface IParams extends ParsedUrlQuery {
    id: string
}

const AboutMeDetail = ({ aboutMeDetail }: IPropsAboutMeDetail) => {
    const { title = '', message = '' } = aboutMeDetail || {};
    const router = useRouter()

    return ( 
        <div className={styles.container}>
            <Head>
                <title>About Me</title>
                <meta name="description about me" content="Generated by create next app" />
            </Head>

            {router.isFallback && <div>Loading...</div>}

            {!router.isFallback && (
                <>
                    <div className={styles.back} onClick={() => router.back()}>&larr; Back</div>
                    <h1>{title}</h1>
                    <p>{message}</p>
                </>
            )}
        </div>
    )
}

export const getStaticPaths: GetStaticPaths = async () => {
    // const baseUrl = process.env.BASE_URL;
    // const res = await fetch(`${baseUrl}/api/about-me`)
    // const aboutMeList = await res.json()
    const aboutMeList = [1,2]
  
    // Get the paths we want to pre-render based on posts
    const paths = aboutMeList.map((about: number) => ({
      params: { id: String(about) },
    }))
  
    // We'll pre-render only these paths at build time.
    // { fallback: blocking } will server-render pages
    // on-demand if the path doesn't exist.
    return { paths, fallback: true }
  }

// automatically will be ISG
export const getStaticProps: GetStaticProps = async (context) => {
    const { id } = context.params as IParams;
    const baseUrl = process.env.BASE_URL;
    const res = await fetch(`${baseUrl}/api/about-me/${id}`)
    const aboutMeDetail = await res.json()

    return {
      props: {
        aboutMeDetail,
      },
      revalidate: 2,
    }
}

export default AboutMeDetail