import { useRouter } from 'next/router'
import Head from 'next/head'
import { GetServerSideProps } from 'next'
import styles from '../styles/Learn.module.css'

interface IPropsExample {
    detailExample: { message: string; id: string }
}

const Example = ({ detailExample }: IPropsExample) => {
    const router = useRouter()
    const { message } = detailExample
    return ( 
        <div className={styles.container}>
            <Head>
                <title>Example</title>
                <meta name="description example" content="Generated by create next app" />
            </Head>

            <div className={styles.back} onClick={() => router.back()}>&larr; Back</div>
            <h1>Example Page</h1>
            <p>{message}</p>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps = async () => {
    const baseUrl = process.env.BASE_URL;
    const res = await fetch(`${baseUrl}/api/example`)
    const detailExample = await res.json()

    // Pass data to the page via props
    return { props: { detailExample } }
  }

export default Example