import { useRouter } from 'next/router'
import Head from 'next/head'
import styles from '../styles/Learn.module.css'

const Learn = () => {
    const router = useRouter()
    return ( 
        <div className={styles.container}>
            <Head>
                <title>Learn</title>
                <meta name="description learn" content="Generated by create next app" />
            </Head>

            <div className={styles.back} onClick={() => router.back()}>&larr; Back</div>
            <h1>Learn Page</h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
        </div>
    )
}

export default Learn